#!/usr/bin/perl

@vars = split(/&/, $ENV{QUERY_STRING});
foreach $var (@vars){
    ($v,$i) = split(/=/, $var);
#$v =~ tr/+/ /;
#$v =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
#$i =~ tr/+/ /;
#$i =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
#$i =~ s/<!--(.|\n)*-->//g;
    if($INFO{$v} ne ""){
    $INFO{$v} .= ",$i";
    }else{
	$INFO{$v} = $i;
    }
}        
$procid=$INFO{PROCID};
$task=$INFO{TASK};

if ($task eq "STOP") {
  unlink ("/tmp/$procid");
  print ("Content-type: text/html\n\n");
  open (HF,"../htdocs/TheEnd.htm");
  while (<HF>) {
    print $_;
    }
  close (HF);
  }  else  {
print ("Content-type: text/html\n\n");
print ("<HTML><HEAD><TITLE>Fortune Cookie</TITLE>");
        
if ($task eq "DEL") {
  unlink ("/tmp/$procid");
  }
if ($task ne "SAME") {
  print ("<META HTTP-EQUIV=\"Refresh\" CONTENT = \"10;URL=http://www.w3oi.org/cgi-bin/fortune\">");
  system("date >/tmp/$$");
  $procid=$$;
  }
print ("</HEAD>\n<BODY BGCOLOR=\"WHITE\"><H3><BR>Your Daily Fortune.......</H3><HR>");
print ("<TABLE BORDER=4 WIDTH=\"100%\" COL=1>");
print ("<TR ><TD VALIGN=\"center\" BGCOLOR=\"Black\"><FONT SIZE=\"+1\" COLOR=\"WHITE\"><PRE>");
open (CF,"/tmp/$procid");
while (<CF>) {
  print $_;
  }
close (CF);  
print '</FONT></PRE></TR></TABLE><HR>';
print '<TABLE ALIGN="center" WIDTH="100%"><TR>';
print "<TD ALIGN=\"center\"><A HREF=\"/cgi-bin/fortune?PROCID=$procid&TASK=DEL\">Another Cookie</A>";
print "<TD ALIGN=\"center\"><A HREF=\"http://w3oi.dyndns.org:1091/cgi-bin/fortune?PROCID=$procid&TASK=SAME\">Stop! I want to read it.</A>";
print "<TD ALIGN=\"center\"><A HREF=\"/cgi-bin/fortune?PROCID=$procid&TASK=STOP\">Get me out of here...</A>";
print '</TR></TABLE><HR><CENTER>';
if ($task eq "SAME") {
  print ("STOPPED!<BR>Click \"Another Cookie\" to resume cookie cycling.");
    } else {
  print ("This page will self destruct shortly...........");
  }
print ("</CENTER></BODY></HTML>\n");
}
